### ISSUE TITLE
[Sublime Text 3] Inline output text moves out below target line

### ISSUE THREAD

**Issue by epszaw** [wallabyjs/quokka#383] opened 2019-06-13 11:24 UTC
### Issue description or question

If you try make output of last line of file output will render incorrectly.

If add empty line below – works normal.

_Outputing from the last line_:

![image](https://user-images.githubusercontent.com/13414205/59428619-6cde1900-8de6-11e9-8c53-f32e7f072e95.png)

_Outputing with following line_:

![image](https://user-images.githubusercontent.com/13414205/59428746-d52cfa80-8de6-11e9-9710-0c1368f6ebfd.png)

Also, errors renders incorrect too in the first case.

### Code editor version

Sublime Text 3 3.2.1 3207

### OS name and version

OSX 10.14.5

**Comment by smcenlly** [comment] 2019-06-13 21:36
Thanks for reporting the issue. Unfortunately, this is by design due to a bug with Sublime phantoms behavior. If the line with adornments is the last line, then the comment displays on the next line instead of the current line.

We raised this in [Sublime technical support forums](https://forum.sublimetext.com/t/inconsistent-sublime-phantoms-behavior/44760) when we discovered it.

When the Sublime Team fixes the bug we will update our Quokka to fix this issue.

**Comment by lamartire** [comment] 2019-06-14 06:58
@smcenlly thank you, can't wait it :)

**Comment by smcenlly** [comment] 2023-03-01 06:15
Closing this issue as this is a bug in Sublime Text and not Quokka. 

We reported it in **Jun 2019** but still not response from the Sublime Text team; feel free to follow up using [this link](https://forum.sublimetext.com/t/inconsistent-sublime-phantoms-behavior/44760)

**Closed by smcenlly** 2023-03-01 06:15 UTC
