### ISSUE TITLE
This very specific code block breaks Quokka

### ISSUE THREAD

**Issue by ffxsam** [wallabyjs/quokka#682] opened 2021-09-21 04:27 UTC
### Issue description or question

This code below breaks Quokka for some reason. If you remove the 2nd `for` loop and then paste that into Quokka, it's totally fine. 🤔  (breaks for TypeScript mode; JavaScript is fine)

### Sample code

```typescript
const plan1 = {
  tracks: -1,
  reels: -1,
  things: -1,
};
const plan2 = {
  tracks: -1,
  reels: -1,
  things: 40,
};

function getBetterQuota(
  q1: Record<string, number>,
  q2: Record<string, number>
) {
  let score1 = 0, score2 = 0;

  for (const value of Object.values(q1)) {
    score1 += value;
  }
  for (const value of Object.values(q2)) {
    score2 += value;
  }

  return { score1, score2 };
}
```

### Quokka.js Console Output

(empty)

### Code editor version

Visual Studio Code v1.60.1

### OS name and version

macOS 11.5.2

**Comment by ArtemGovorov** [comment] 2021-09-21 04:43
The issue is related to https://github.com/microsoft/vscode/issues/132431. It's working as expected in VS Code Insiders and will is fixed in VS Code v1.60.2.

**Closed by ArtemGovorov** 2021-09-21 04:43 UTC
