### ISSUE TITLE
run quokka on whole project instead of one file

### ISSUE THREAD

**Issue by daggett206** [wallabyjs/quokka#117] opened 2017-11-15 10:38 UTC
Hi, I'm a quokka pro user, just want to ask do you plan to add functionality for running quokka on a whole project instead of one file as for now? As I asked [here](https://github.com/wallabyjs/quokka/issues/74), it is unable to use quokka with angular (if yes, please provide a description how). Also, I really want to use all features in all imported files too, not only in entry .js file.

**Comment by ArtemGovorov** [comment] 2017-11-15 10:51
Hello,

It is a good question.

Quokka was designed to only run a single entry file. At this stage we don't have plans to extend it to display coverage and live results on multiple files. Supporting the requested features requires to run the whole build process of a particular project, via webpack and other module bundlers, support browsers (apart from node.js), etc. It's out of scope for the project, which is positioned as a scratchpad.

Having said that, our another product [Wallaby.js](https://wallabyjs.com/) supports all that and is operating on a project level. It does require a per project config file that essentially reflects the project build process.

**Closed by ArtemGovorov** 2017-11-15 10:51 UTC
Labels: question

**Comment by daggett206** [comment] 2017-11-15 11:02
Thanks for so quick answer, as far as I understand wallabyjs is able to do whatever quokkajs can, and wallaby not only about running tests?

**Comment by ArtemGovorov** [comment] 2017-11-15 11:11
Wallaby is a test runner, so its primary purpose is to run tests. Tests, as entry points, execute the bulk of your code, so Wallaby is able to display the code coverage (and live execution results) where your tests can reach. In case of Quokka, if code coverage and live results in multiple files were supported, most of your app files would just be grey (because nothing executes those code paths), so no live results would be available. Unless you create an entry Quokka file that would instantiate your app modules and call their methods, etc. This is essentially what unit tests do, and that's why the whole project support feature makes much more sense for a test runner (like Wallaby), rather that for a scratchpad like Quokka.

Quokka and Wallaby are two different products for different purposes. Each of them has unique features suitable for particular scenarios.

Hope it makes sense.

**Comment by NathanielHill** [comment] 2018-07-05 00:21
New Pro user here! Would it be possible for example, to run Quokka by default on all `.js` files opened in VSCode?

**Comment by ArtemGovorov** [comment] 2018-07-05 00:47
@NathanielHill It's not possible now, I suspect that not many users would want the tool to always run, so we could add the feature but definitely under a setting with `false` value by default.

**Comment by NathanielHill** [comment] 2018-07-05 00:49
Okay, that would be a great feature for me. Maybe it could be done with a VSCode hook? I'm also trying to run Wallaby and Quokka simultaneously in a project and it appears only one will run on a file at a time?

**Comment by ArtemGovorov** [comment] 2018-07-05 00:53
@NathanielHill 

> Maybe it could be done with a VSCode hook?

Can definitely be done via an extension. For example there's one that can run any command on the IDE start https://github.com/GabiGrin/vscode-auto-run-command, maybe there's one that can run commands on file open.

> I'm also trying to run Wallaby and Quokka simultaneously in a project and it appears only one will run on a file at a time?

They should both run, but due to VS Code decorations limitation, only one set of decorations can be displayed in the editor, so you'll either see gutter icons and inline message from one tool or another (the same is true for other tools utilising the gutter/inline decorations).

**Comment by NathanielHill** [comment] 2018-07-05 01:06
Awesome plugin! Installed and configured it already, now just need to find one to run Quokka on file open. Was having trouble trying to run Quokka in jest test files (jest throws a bunch of stuff on the `global` object and I couldn't find a simple way to import them directly). I noticed there that the gutter didn't work with both. However, I don't think there's much use for Quokka in that environment anyways.
