### ISSUE TITLE
Evaluation with comment /*?*/ isn't working for optional chaining in Webstorm

### ISSUE THREAD

**Issue by aelyseev** [wallabyjs/quokka#547] opened 2020-10-02 11:24 UTC
### Issue description or question
Live output comment `/* ? */` isn't working for expressions, which contains optional chaining. But in the console, the expression evaluates correctly. Expressions without optional chaining work as expected. 

### Sample code

scratch file
```javascript
const { URLSearchParams } = require('url');

const searchParams = new URLSearchParams;
searchParams.get('type')?.split(',') /*?*/
```

.quaokka
```
{
  "babel": {
    "plugins": ["@babel/plugin-proposal-optional-chaining", "@babel/plugin-proposal-nullish-coalescing-operator"]
  },
  "plugins": ["jsdom-quokka-plugin"]
}

```

### Quokka.js Console Output

```
Quokka #1 (node: v10.18.0, babel: v7.6.4, plugins: jsdom-quokka-plugin)

URLSearchParams {} at new URLSearchParams() quokka.jsx:3:0

[ 'A', 'B' ] at (_searchParams$get = searchParams.get('m... quokka.jsx:5:0

```

### Code editor version

Webstorm v 2020.2.2

### OS name and version

OSX 10.15.6

### Preview
<img width="400" alt="preview" src="https://user-images.githubusercontent.com/4263131/94917100-95e15c00-04b8-11eb-9848-c3e6370f6be9.png">

**Comment by ArtemGovorov** [comment] 2020-10-03 06:44
Thanks for the report. The issue is fixed in the latest plugin v1.0.257.

**Closed by ArtemGovorov** 2020-10-03 06:44 UTC
