### ISSUE TITLE
Clicking on 'Pro' link from Quokka Output gives GitHub's 404 Page

### ISSUE THREAD

**Issue by chrispstephens** [wallabyjs/quokka#139] opened 2017-12-30 11:50 UTC
### Issue description or question
Ctrl + click to follow link in Quokka output console takes you to a GitHub's 404 page.
```​​​​
### Sample code

```javascript
setTimeout(() => {}, 1000) /* ?. */

```

### Quokka.js Console Output

```
Quokka #1 (node: v8.9.3)​​​​
​​​​​​​​​​
​​​​​Live Comments only supported in 'Pro' edition, see https://quokkajs.com/pro/​​​​​
  at ​​​setTimeout(() => { }, 1000)​​​ ​scratch.js:1:0​
```

### Code editor version

Visual Studio Code v1.19.1

### OS name and version

Windows 10 + Chrome as default browser

### Postscript
If you look very carefully in the Chrome address bar you will find there are invisible characters at the end of the URL. If you put cursor at the end of the URL you can delete 5 characters before the trailing `\` to get to the right URL. I only found this quickly because I spent previously copied something from the Wallaby output into my code and then spent hours debugging the Code before I found I had inadvertently copied some invisible characters into my source!

**Comment by ArtemGovorov** [comment] 2017-12-31 00:05
Thanks for the bug report. The issue is fixed in the latest v1.0.88.

**Closed by ArtemGovorov** 2017-12-31 00:05 UTC
Labels: bug
