### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by hileroy132** [wallabyjs/quokka#473] opened 2020-04-22 05:11 UTC
- Issue Type: `Performance`
- Extension Name: `quokka-vscode`
- Extension Version: `1.0.288`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.44.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\leroy\WallabyJs.quokka-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by ArtemGovorov** [comment] 2020-04-22 05:13
Please attached the `C:\Users\leroy\WallabyJs.quokka-vscode-unresponsive.cpuprofile.txt` file mentioned in the issue description.

**Comment by smcenlly** [comment] 2020-04-22 22:25
Closing this issue as we do not have additional details. Likely a duplicate of https://github.com/wallabyjs/quokka/issues/444.

From previous issue:

> Thanks for providing the CPU profile. We can see that the high CPU occurs when unzipping our [interactive examples](https://github.com/wallabyjs/interactive-examples). The high CPU is occurring when trying to close the file handles after the interactive examples have been uncompressed and have been written to disk. During this operation we are writing 519 JavaScript files that are on average 280 bytes in length so this shouldn't be causing a problem.
>
> **The high CPU was likely caused by a virus scanner or system-related operation. A virus scanner is more likely the cause given that these are JavaScript snippets.**
> 
> Since the cause of this problem occurs outside of Quokka's code-base we are going to close this issue. If we get a similar report from others in the future, we may re-consider how our interactive samples are stored to minimize interruption by virus scanners.

**Closed by smcenlly** 2020-04-22 22:25 UTC
Labels: more info is required
