### ISSUE TITLE
['1.1', '2.2e2', '3e300'].map(Number);

### ISSUE THREAD

**Issue by DmitriyMalayev** [wallabyjs/quokka#782] opened 2022-05-19 03:13 UTC
Hi everyone, 

I love your extension. 
I am following along mdn and came across a bug (I think)

['1.1', '2.2e2', '3e300'].map(Number)  outputs NaN
in the node console it outputs correctly 

Welcome to Node.js v16.13.2.
Type ".help" for more information.
> ['1.1', '2.2e2', '3e300'].map(Number)
[ 1.1, 220, 3e+300 ]

### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: Yes/No

### Sample code

```javascript
// paste the code you are running here
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
```

### Code editor version

Visual Studio Code v1.?
Webstorm v?
Atom v1.?

### OS name and version

Windows
OSX
Linux

**Comment by NikGovorov** [comment] 2022-05-19 04:14
We couldn't reproduce the issue.

**Comment by NikGovorov** [comment] 2022-05-19 04:15
Here is a code clip showing that it works as expected 
![image](https://user-images.githubusercontent.com/129254/169203026-659bc5e9-41b4-49e9-b2a9-b09038d7b0e4.png)
https://codeclip.io/9aWpGw5q

**Comment by smcenlly** [comment] 2022-05-23 00:54
Closing this issue as it appears to be working as expected. If you can reproduce the error, please reply with steps to reproduce it and we will reopen the issue.

**Closed by smcenlly** 2022-05-23 00:54 UTC
