### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by HiepPP** [wallabyjs/quokka#846] opened 2022-12-12 20:21 UTC
- Issue Type: Performance
- Extension Name: WallabyJs.quokka-vscode
- Extension Version: v1.0.515
- OS Version: MacOS 13.0.1 (22A400)
- VS Code version: 1.74.0
Hi team, I have purchased quokka pro, after 1 week daily using, I found a problem of quokkajs when it work together with other extension. For detail, when anable quokkajs with `Import Cost` by Wix (ver v3.3.0), then import some library (import axios from "axios") high CPU load happened (over 100%). Here my cpuprofile, please check, thank you.

[quokka.txt](https://github.com/wallabyjs/quokka/files/10211724/quokka.txt)

```
import axios from "axios";

const plus = (a: number, b: number) => a + b;

plus(1, 5);

const minus = (a: number, b: number) => a - b;

minus(1, 4);


const get = async () => {
    const res = await axios.get("https://api.publicapis.org/entries");
    console.log(res.data);
}

get();
```

**Comment by smcenlly** [comment] 2022-12-12 23:27
We are fairly certain that the problem that you are experiencing is caused by [wix.vscode-import-cost](https://marketplace.visualstudio.com/items?itemName=wix.vscode-import-cost) and not Quokka. Your CPU profile shows a lot of `lstat` calls to the file system. The trace is limited but we're guessing this is coming from the Import Cost package because Quokka doesn't make any of those calls.

Under the covers, when you install a dependency with Quokka, Quokka is just running `npm install {packageName}` and does not do any other processing of the package during installation.

To confirm that the problem is not related to Quokka, can you please try the following:
1. With Quokka installed, uninstall or disable `wix.vscode-import-cost` and check whether you still have a problem when importing the file.

_You should not see any high CPU at this point in time_

2. With `wix.vscode-import-cost` installed, uninstall or disable Quokka and then open the file with the same contents in VS Code. Make sure the focus is in the text editor containing the `import` statement. In a separate terminal instance, install `axios` using your package manager (e.g. `npm install`).

_You should see high CPU when the package is installing_

---

There are a number of seemingly related issues in the Wix Import Cost issue registry:

https://github.com/wix/import-cost/issues/274
https://github.com/wix/import-cost/issues/272
https://github.com/wix/import-cost/issues/266

---

We are going to close this issue. Suggest reporting to https://github.com/wix/import-cost/.

**Closed by smcenlly** 2022-12-12 23:27 UTC
