### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by bondz** [wallabyjs/quokka#32] opened 2017-04-05 22:55 UTC
The plugin doesn't work offline. 

### Steps to reproduce.
Go Offline. Start a new Quokka JS or TS file. Nothing happens.

### Code and Plugin Version
Code: 1.10.2 
Quokka: 1.0.23
### OS Version
Windows 10

**Comment by ArtemGovorov** [comment] 2017-04-06 04:02
Thanks for the report. The issue is fixed in v1.0.25.

**Closed by ArtemGovorov** 2017-04-06 04:02 UTC
Labels: bug
