### ISSUE TITLE
Quokka kills `cmd+k` clearing the Integrated Terminal in VSCode

### ISSUE THREAD

**Issue by cherealnice** [wallabyjs/quokka#26] opened 2017-03-29 15:51 UTC
### Issue description or question
When Quokka is active, you can no longer clear the Integrated Terminal with `cmd+k` in VSCode.

### Quokka.js file
N/A

### Sample repository link
N/A

### Quokka.js Console Output
N/A

### Code editor version
Visual Studio Code v1.10.2
Quokka 1.0.18

### OS name and version
OSX 10.12.3

**Comment by ArtemGovorov** [comment] 2017-03-30 01:20
Thanks for the report. The issue is fixed in the v1.0.19.

**Closed by ArtemGovorov** 2017-03-30 01:20 UTC
