### ISSUE TITLE
Atom (Mac): Live Comments only supported in 'Pro' edition

### ISSUE THREAD

**Issue by NoahCardoza** [wallabyjs/quokka#141] opened 2018-01-02 19:29 UTC
### Issue description or question

Unless I misunderstood, `Live Feedback` is different than `Live Comments`. Shouldn't `Live Feedback` work in the free version? It seems Quokka might be experiencing some kind of hiccup here, or I'm just wrong... Anyhow, I figured this was the place to ask.

### Sample code

```javascript
const quokka = {
  answer: 42
}
quokka  // Live Comments only supported in 'Pro' edition, see https://quokkajs.com/pro/ for more details
```

### Quokka.js Console Output

```
Live Comments only supported in 'Pro' edition, see https://quokkajs.com/pro/ for more details at quokka schema.js:4:0
```

### Code editor version

Atom v1.23.1

### OS name and version

OSX Seria (10.12.6)

**Comment by mpowell90** [comment] 2018-01-02 21:39
I'm finding the same issue.
using VSCode extension.

**Comment by ArtemGovorov** [comment] 2018-01-02 23:07
`Live Feedback` was disabled by mistake. The issue is fixed in the latest Quokka version.

**Closed by ArtemGovorov** 2018-01-02 23:07 UTC

**Comment by NoahCardoza** [comment] 2018-01-03 02:02
Ah, glad I asked! Thanks!

**Comment by Cybersifter13** [comment] 2019-04-12 19:36
: just installed Quokka on atom As above, i get the message that Live Feedback is only available in the PRO version; the console is opened bt nothing appears in it; not even console.log

**Comment by ArtemGovorov** [comment] 2019-04-13 00:27
@Cybersifter13 The message is expected if you are using live comments anywhere in your document. Plain `console.log` should just work though. Could you please share some more details, such as your OS, Quokka file content, actions you perform? We can't reproduce the issue with plain `console.log`:

<img width="366" alt="Screen Shot 2019-04-13 at 10 24 55 am" src="https://user-images.githubusercontent.com/979966/56072071-a4284d80-5dd6-11e9-8d7c-cc9d9652ce11.png">
