### ISSUE TITLE
Sublime Text Warnings

### ISSUE THREAD

**Issue by marcoSven** [wallabyjs/quokka#500] opened 2020-06-15 14:48 UTC
### Issue description or question
Sublime Text Console
reloading python 3.3 plugin Quokka.quokka
<string>:404: SyntaxWarning: name 'is_pro_mode' is assigned to before global declaration
<string>:406: SyntaxWarning: name 'has_global_config' is assigned to before global declaration

### Code editor version

ST4

### OS name and version

OSX

**Comment by ArtemGovorov** [comment] 2020-06-16 01:02
Thanks for letting us know. The issue is fixed and the the fix will be released in the next package version.

**Closed by ArtemGovorov** 2020-06-16 01:02 UTC
