### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by joguarino** [wallabyjs/quokka#444] opened 2019-12-13 12:29 UTC
- Issue Type: `Performance`
- Extension Name: `quokka-vscode`
- Extension Version: `1.0.265`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.41.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\g.guarino\WallabyJs.quokka-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smcenlly** [comment] 2019-12-13 20:37
@joguarino - could you please provide us with the file: `⚠️C:\Users\g.guarino\WallabyJs.quokka-vscode-unresponsive.cpuprofile.txt`?

**Comment by joguarino** [comment] 2019-12-15 15:46
@smcenlly , sure, try to pick it from here: https://tsspa-my.sharepoint.com/:t:/g/personal/g_guarino_teamsystem_com/ETijNqC8YQFOk340_rZm9k0BFj0sQlLu2rV79pbOTr77fw?e=eZCTiX

**Comment by smcenlly** [comment] 2019-12-15 22:56
Thanks for providing the CPU profile. We can see that the high CPU occurs when unzipping our [interactive examples](https://github.com/wallabyjs/interactive-examples). The high CPU is occurring when trying to close the file handles after the interactive examples have been uncompressed and have been written to disk. During this operation we are writing 519 JavaScript files that are on average 280 bytes in length so this shouldn't be causing a problem.

The high CPU was likely caused by a virus scanner or system-related operation. A virus scanner is more likely the cause given that these are JavaScript snippets.

Since the cause of this problem occurs outside of Quokka's code-base we are going to close this issue. If we get a similar report from others in the future, we may re-consider how our interactive samples are stored to minimize interruption by virus scanners.

**Closed by smcenlly** 2019-12-15 22:56 UTC

**Comment by joguarino** [comment] 2019-12-18 15:43
Ok, thanks for the answer. Actually, the problem occurred on my work laptop, which has several virus scanners and similar, due to company policy.
