### ISSUE TITLE
the text is not transferred to the function brackets in the js file with the quokka enabled.

### ISSUE THREAD

**Issue by saneq1** [wallabyjs/quokka#327] opened 2019-02-11 21:46 UTC
the text is not transferred to the function brackets in the js file with the quokka enabled. windows
![rockb](https://user-images.githubusercontent.com/20462876/52595749-a108f380-2e5f-11e9-8a63-8ef85ccf699e.png)
![htlbt](https://user-images.githubusercontent.com/20462876/52595753-a2d2b700-2e5f-11e9-8198-bb8c2bdff245.png)

**Comment by smcenlly** [comment] 2019-02-11 22:02
It is expected behavior that `console.log` will not have any logging in your second example. This is because getElement() results in an error and the `console.log` line of code is never executed.

**Comment by saneq1** [comment] 2019-02-11 22:07
text is not transferred to brackets!!!!
![hfghf](https://user-images.githubusercontent.com/20462876/52596896-81bf9580-2e62-11e9-863c-7d6133cabcc0.PNG)

**Comment by saneq1** [comment] 2019-02-11 22:09
if quokka is turned off then the text is transferred to console.log (here), if it is turned off, it is not transferred.

**Comment by smcenlly** [comment] 2019-02-11 22:13
Sorry - we're not sure what steps you're taking and what you're trying to do. Can you please detail with step-by-step instructions to duplicate?

**Comment by smcenlly** [comment] 2019-02-11 22:18
When you respond, can you also please detail the VS Code extensions that you are using.

**Comment by saneq1** [comment] 2019-02-11 22:18
I cannot move the selected code to the function call brackets or console.log (here) in the js file with quokka enabled

**Comment by saneq1** [comment] 2019-02-11 22:21
![31](https://user-images.githubusercontent.com/20462876/52597605-72d9e280-2e64-11e9-84f1-4dba10a6bd24.PNG)
![default](https://user-images.githubusercontent.com/20462876/52597608-74a3a600-2e64-11e9-9f25-1b1511b78d50.PNG)

**Comment by saneq1** [comment] 2019-02-11 22:28
problem with plugin "bracket pair colorizer 2"

**Comment by smcenlly** [comment] 2019-02-11 22:32
OK - thanks for the update. I'll close this issue.

**Closed by smcenlly** 2019-02-11 22:32 UTC

**Comment by saneq1** [comment] 2019-02-11 22:53
problem with plugin "bracket pair colorizer 2" "bracket pair colorizer" "rainbow bracket"

**Comment by saneq1** [comment] 2019-02-11 22:53
How can this be fixed?

**Comment by smcenlly** [comment] 2019-02-11 23:47
We had a look through the `bracket pair colorizer` source code and couldn't identify the cause of the problem. It seems that there's a conflict between Quokka decorations and the decorations for these plugins. In addition, these plugins seem to be overriding default text selection so that may also be related. I would suggest asking @CoenraadS, the author of `bracket pair colorizer` and `bracket pair colorizer 2` for their input. From what we saw, we expect the problem would be easy to duplicate with multiple text decorations on the same line (may even be a current limitation of VS Code)

**Comment by CoenraadS** [comment] 2019-02-12 08:10
I'm interested in looking into this, but I have not used this extension before. What is the problem and how can I reproduce it?

**Comment by smcenlly** [comment] 2019-02-12 10:49
@CoenraadS - we provide a community/paid extension for VS Code that provides a rapid prototyping playground for JavaScript and TypeScript within VS Code. [https://quokkajs.com/](https://quokkajs.com/)

You can download the community version through the extension store. We are happy to provide you with a license key to upgrade to the PRO version as thanks for your time in identifying the problem (email us at [hello@wallabyjs.com](mailto:hello@wallabyjs.com)).

To duplicate the problem.

1. Install the Quokka Extension (if prompted, select to use the free `Community` edition)
2. Launch a new Quokka Javascript file using our VS Code command, `>Quokka.js: New JavaScript File`.
3. Set the file content to:

```javascript
console.log()

getSelection()
```

4. Select `getSelection()`
5. Attempt to Drag and Drop the `getSelection()` text within the `console.log()` braces, i.e. console.log(`here`).

--

What we've seen is that the drag and drop fails. We took a look at `bracket pair colorizer` v1 source code, but couldn't work out exactly why it was failing. If you struggle to work out why, we can help by providing an opensource sample to reproduce the problem.

**Comment by saneq1** [comment] 2019-02-12 11:07
same via > Quokka.js: New JavaScript File . if" bracket pair colorizer " is disabled, it works by dragging and dropping

**Comment by saneq1** [comment] 2019-02-12 11:08
I can make a video
