### ISSUE TITLE
tsconfig-paths dont work with esm modules

### ISSUE THREAD

**Issue by bhvngt** [wallabyjs/quokka#711] opened 2021-11-09 09:25 UTC
### Issue description or question
I am using `quokkajs` from an intellij module that is configured as `esm` package.

My `.quokka` file  is
```
{
  "nativeEsm": true,
  "env": {
    "params": {
      "runner": "--experimental-specifier-resolution=node"
    }
  }
}
```

Since as per this [issue](https://github.com/dividab/tsconfig-paths/issues/122) `tsconfig-paths` does not work with `esm` modules, I am using [typescript-transform-paths](https://www.npmjs.com/package/typescript-transform-paths) to transform path mappings. However, I believe is not supported by `quokka`.

Just wanted to check if you  have plan to support path mapping functionality using this module or through some alternate form of solution.

`tsconfig.json` is
```json
	"compilerOptions": {
		"target": "esnext",
		"module": "esnext",
		"plugins": [
			{ "transform": "typescript-transform-paths" },
			{ "transform": "typescript-transform-paths", "afterDeclarations": true }
                 ],
		"baseUrl": "./",
		"paths": {
			"$src/*": ["src/*"]
		}
         }

```

Is this issue related to Quokka not outputting the expected results of your code?: Yes

### Sample code

`src/m1/a.ts`
```typescript
export const x = "Hello";
```
`src/m2/b.ts`
```typescript
import {x} from "$src/m1/a.";
console.log(x);
```

### Quokka.js Console Output

```
Cannot find module '/Volumes/DATA/User/Projects/p1/src/m1/a.js' imported from ./src/m2/b.js
```

### Code editor version

intellij 2021.2.3

### OS name and version
OSX

**Comment by smcenlly** [comment] 2021-11-09 23:21
Could you please detail how you are running your code using the command line so that we can see how it's executing outside of Quokka?

**Comment by bhvngt** [comment] 2021-11-10 05:05
There is a pending issue LeDDGroup/typescript-transform-paths#134 that is blocking `esm` compatibility with `ts-node` and `typescript-transform-paths`. Hopefully it will get fixed soon since the blocking issue TypeStrong/ts-node#1439 at `ts-node` repo has been merged.

**Comment by smcenlly** [comment] 2021-11-10 22:13
> There is a pending issue [LeDDGroup/typescript-transform-paths#134](https://github.com/LeDDGroup/typescript-transform-paths/issues/134) that is blocking `esm` compatibility with `ts-node` and `typescript-transform-paths`. Hopefully it will get fixed soon since the blocking issue [TypeStrong/ts-node#1439](https://github.com/TypeStrong/ts-node/pull/1439) at `ts-node` repo has been merged.

Since the issue is not related to Quokka itself and it is not currently possible to run the code either with Quokka or outside of Quokka, we will close the issue. If/when it is possible to run the code outside of Quokka, if it doesn't work for you please raise a feature request or else respond to this issue and we will re-open and investigate for you.

**Closed by smcenlly** 2021-11-10 22:13 UTC
Labels: more info is required

**Comment by bhvngt** [comment] 2021-11-11 06:27
@smcenlly There are some [custom loaders](https://github.com/TypeStrong/ts-node/discussions/1450#discussion-3563207) which uses combination of `ts-node` and `tsconfig-paths`. I haven't tried them but was curious if that is something that can be passed to quokka's `env.params.runner` option via `--loader` flag as a user defined configuration?

**Comment by smcenlly** [comment] 2021-11-11 21:33
In order to operate with ESM, Quokka has its own ESM loader. Part of the loader includes integration to support `ts-node`'s ESM functionality. We have no plans at this stage to support custom ESM loaders for Quokka.

At this point in time, while we support ESM, we are careful of how much we expose outside of our internals as the node API is experimental and has already broken once (in the last couple of months).

If you can run your code with `ts-node` outside of Quokka, we can investigate support for this for you.

**Comment by bhvngt** [comment] 2021-11-12 07:30
Make sense @smcenlly. Making path aliasing work with `esm`, `ts-node`, `tsconfig-paths`  have been quite crazy.  Will ping you if I find something that works well with `ts-node`
