### ISSUE TITLE
Quokka with "ts-node" installed produces SWC error

### ISSUE THREAD

**Issue by Filyus** [wallabyjs/quokka#925] opened 2024-01-03 15:49 UTC
### Issue description or question
The error happens when `ts-node` in active project is installed.
This happens even when the code and `tsconfig.json` are empty.

Installing `SWC` helps:
```
npm i -D @swc/cli @swc/core
```

Perhaps, instead of the error, this is better to write a suggestion to install the SWC, disable it with a Quokka settings or even disable it automatically when the SWC is not installed.

### Quokka.js Console Output

```
609\dist\wallaby\node_modules\@swc\wasm threw an error when attempting to validate swc compiler options. 
You may be using an old version of swc which does not support the options used by ts-node. 
Try upgrading to the latest version of swc. 
Error message from swc: 
undefined 
  ​​​​​at ​​​​​​​​createVariant​​​ ​./node_modules/ts-node/src/transpilers/swc.ts:259​
  ​​​​​at ​​​​​​​​createSwcOptions​​​ ​./node_modules/ts-node/src/transpilers/swc.ts:201​
  ​​​​​at ​​​​​​​​create​​​ ​./node_modules/ts-node/src/transpilers/swc.ts:54​
  ​​​​​at ​​​​​​​​createTranspiler​​​ ​./node_modules/ts-node/src/index.ts:784​
  ​​​​​at ​​​​​​​​createTranspileOnlyGetOutputFunction​​​ ​./node_modules/ts-node/src/index.ts:1341​
  ​​​​​at ​​​​​​​​createFromPreloadedConfig​​​ ​./node_modules/ts-node/src/index.ts:1404​
  ​​​​​at ​​​​​​​​create​​​ ​./node_modules/ts-node/src/index.ts:624​
  ​​​​​at ​​​​​​​​Object.register​​​ ​./node_modules/ts-node/src/index.ts:591
```

There also related issue when `"swc": true"` is specified in `tsconfig.json`:
```
Cannot specify both 'swc' and 'transpiler' options.  'swc' uses the built-in swc transpiler. 
```

### Code editor version

Visual Studio Code v1.85.1
ts-node: 10.9.2

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment] 2024-01-03 23:02
Thanks for the report. 

We will investigate the fix mid next week.

In the meantime you may [disable SWC](https://quokkajs.com/docs/configuration.html#using-swc-for-dependency-compilation) with a Quokka configuration setting.

**Comment by rcoundon** [comment] 2024-01-05 10:15
I'm seeing the same issue in WebStorm 2023.3.2 with Quokka 1.0.422

```
/Users/rosscoundon/Library/Application Support/JetBrains/WebStorm2023.3/plugins/quokka-intellij/dist/node_modules/@swc/wasm threw an error when attempting to validate swc compiler options.
You may be using an old version of swc which does not support the options used by ts-node.
Try upgrading to the latest version of swc.
Error message from swc:
undefined
	at createVariant ./node_modules/.pnpm/ts-node@10.9.2_@types+node@20.10.6_typescript@5.3.3/node_modules/ts-node/src/transpilers/swc.ts:259
	at createSwcOptions ./node_modules/.pnpm/ts-node@10.9.2_@types+node@20.10.6_typescript@5.3.3/node_modules/ts-node/src/transpilers/swc.ts:201
	at create ./node_modules/.pnpm/ts-node@10.9.2_@types+node@20.10.6_typescript@5.3.3/node_modules/ts-node/src/transpilers/swc.ts:54
	at createTranspiler ./node_modules/.pnpm/ts-node@10.9.2_@types+node@20.10.6_typescript@5.3.3/node_modules/ts-node/src/index.ts:784
	at createTranspileOnlyGetOutputFunction ./node_modules/.pnpm/ts-node@10.9.2_@types+node@20.10.6_typescript@5.3.3/node_modules/ts-node/src/index.ts:1341
	at createFromPreloadedConfig ./node_modules/.pnpm/ts-node@10.9.2_@types+node@20.10.6_typescript@5.3.3/node_modules/ts-node/src/index.ts:1404
	at create ./node_modules/.pnpm/ts-node@10.9.2_@types+node@20.10.6_typescript@5.3.3/node_modules/ts-node/src/index.ts:624
	at Object.register ./node_modules/.pnpm/ts-node@10.9.2_@types+node@20.10.6_typescript@5.3.3/node_modules/ts-node/src/index.ts:591
```

**Comment by smcenlly** [comment] 2024-01-10 06:27
This issue has been addressed in the latest version of Quokka for both VS Code and JetBrains editors. Please update to the latest version(s) if you're still encountering these problems.

**Closed by smcenlly** 2024-01-10 06:27 UTC

**Comment by loganpowell** [comment] 2024-01-11 17:58
Works like a charm. Thank you!!

**Comment by darioprinc** [comment] 2024-02-16 14:43
hello, disabling swc in quokka config.json temporarily solves the issue:

`"ts":{"swc":false}`

Output:

> ​​​​​Quokka PRO 'Untitled-1.ts' (node: v18.19.0, TypeScript: v5.1.6)​​​​
> 
> 123 ​​​​​at ​​​​​​quokka.ts:2:1​

however without it the issue persists:
1. open VSCode
2. \>Quokka.js: New TypeScript File
3. Output:

> Quokka PRO 'Untitled-3.ts' (node: v18.19.0, TypeScript: v5.1.6 + swc)​​​​
>  
> .\node_modules\@swc\core\index.js threw an error when attempting to validate swc compiler options. 
> You may be using an old version of swc which does not support the options used by ts-node. 
> Try upgrading to the latest version of swc. 
> Error message from swc: 
> Failed to deserialize buffer as swc::config::Options 
> JSON: {"sourceMaps":true,"module":{"type":"commonjs","noInterop":false,"strictMode":true,"ignoreDynamic":false},"swcrc":false,"jsc":{"parser":{"syntax":"typescript","tsx":false,"decorators":false,"dynamicImport":true,"importAssertions":true},"target":"es2015","transform":{"legacyDecorator":true,"react":{"throwIfNamespace":false,"useBuiltins":false,"importSource":""},"useDefineForClassFields":false},"keepClassNames":false,"experimental":{"keepImportAttributes":true,"emitAssertForImportAttributes":true}}} 
>  
> Caused by: 
>     unknown field `keepImportAttributes`, expected one of `plugins`, `keepImportAssertions`, `cacheRoot`, `disableBuiltinTransformsForInternalTesting` at line 1 column 502

note: \>Quokka.js: New **JavaScript** File works fine

**Comment by smcenlly** [comment] 2024-02-19 23:47
@darioprinc - can you please share your `package.json` for your project that had the problem?

**Comment by darioprinc** [comment] 2024-02-21 12:48
hi @smcenlly, I suppose you are after dependencies?

```
"devDependencies": {
  "@babel/core": "^7.16.12",
  "@babel/eslint-parser": "^7.16.5",
  "@babel/plugin-proposal-class-properties": "^7.16.7",
  "@babel/preset-env": "^7.16.11",
  "@babel/preset-react": "^7.16.7",
  "@badeball/cypress-cucumber-preprocessor": "^16.0.3",
  "@bahmutov/cypress-esbuild-preprocessor": "2.1.5",
  "@cypress/grep": "^3.1.3",
  "@types/pdf-parse": "^1.1.1",
  "@types/ssh2-sftp-client": "^9.0.3",
  "@typescript-eslint/eslint-plugin": "^5.14.0",
  "@typescript-eslint/parser": "^5.14.0",
  "babel-plugin-transform-import-meta": "^2.2.0",
  "codeowners": "^5.1.1",
  "commander": "^10.0.0",
  "cross-env": "^7.0.3",
  "cypress": "13.6.3",
  "cypress-fail-fast": "^7.0.0",
  "cypress-mochawesome-reporter": "^3.8.0",
  "cypress-multi-reporters": "^1.6.4",
  "cypress-on-fix": "^1.0.2",
  "cypress-real-events": "^1.7.6",
  "cypress-timestamps": "^1.2.3",
  "date-fns": "^2.30.0",
  "esbuild": "^0.15.10",
  "eslint": "^8.8.0",
  "eslint-config-prettier": "^8.4.0",
  "eslint-plugin-cypress": "^2.15.1",
  "eslint-plugin-import": "^2.26.0",
  "eslint-plugin-json": "^3.1.0",
  "eslint-plugin-prettier": "^4.0.0",
  "eslint-plugin-react": "^7.28.0",
  "eslint-plugin-react-hooks": "^4.3.0",
  "eslint-plugin-simple-import-sort": "^7.0.0",
  "find-test-names": "^1.28.14",
  "http-proxy": "^1.18.1",
  "husky": "^8.0.1",
  "lerna": "^5.5.4",
  "lerna-audit-yarn": "^1.1.1",
  "license-checker": "^25.0.1",
  "lint-staged": "^13.0.3",
  "mammoth": "^1.5.1",
  "markdown-it": "^13.0.1",
  "mocha-junit-reporter": "^2.0.2",
  "mysql2": "^3.6.2",
  "node-xlsx": "^0.21.0",
  "npm-run-all": "^4.1.5",
  "pdf-parse": "^1.1.1",
  "prettier": "2.8.7",
  "rimraf": "^3.0.2",
  "shelljs": "^0.8.5",
  "ssh2-sftp-client": "^9.1.0",
  "typescript": "^4.5.5"
}
```

**Comment by smcenlly** [comment] 2024-02-21 23:57
@darioprinc - yes, I was keen to see your dependencies. Are these all of your dependencies?

I want to confirm that these are the same dependencies for the project where you had the issue?

Your Quokka output you provided above shows:

```
Quokka PRO 'Untitled-3.ts' (node: v18.19.0, TypeScript: v5.1.6 + swc)​​​​
```

When I use your dependencies with a fresh installation of your packages, I get:

```
​​​​​Quokka PRO 'index.ts' (node: v18.19.0, TypeScript: v4.9.5 + swc)​​​​
```

I'm wondering where the `typescript@5.1.6` version is coming from. Quokka ships with `typescript@5.3.2` and your dependencies say `typescript@^4.5.5`. This may be related to why the `swc` integration is failing.

**Comment by smcenlly** [comment] 2024-02-23 00:33
@darioprinc - we can't reproduce the problem. We're happy to investigate further but we will need you to provide a sample project that breaks in the same way. Can you please let us know your version of Quokka? You need to be using a version of Quokka released after January 10th, 2024.

**Comment by darioprinc** [comment] 2024-02-23 15:22
@smcenlly Quokka version is v1.0.627

**Comment by smcenlly** [comment] 2024-02-24 00:50
That version should not have the problem. Can you please provide a sample project that breaks in the same way?
