### ISSUE TITLE
Support ANSI color escape sequences

### ISSUE THREAD

**Issue by Faq** [wallabyjs/quokka#656] opened 2021-06-27 08:00 UTC
### Issue description or question
Quokka prints all in one default color by not applying [Chalk style](https://www.npmjs.com/package/chalk)

Terminal in VSCode shows it correct:
![image](https://user-images.githubusercontent.com/322016/123537132-98669e80-d736-11eb-9784-a277c8cbcb29.png)

### Sample code

```javascript
console.log(
  chalk.green.bold("Game started : \n") +
    "                              1 | 2 | 3 \n" +
    chalk.red.bold("                              --------- \n") +
    "                              4 | 5 | 6 \n" +
    "                              --------- \n" +
    "                              7 | 8 | 9 \n"
  //)
);
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
node: v14.17.0, TypeScript: v4.3.4, plugins: jsdom-quokka-plugin
```
![image](https://user-images.githubusercontent.com/322016/123537143-a61c2400-d736-11eb-9fff-3c17410a1e6c.png)

### Code editor version
Version: 1.57.1 (user setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043
### OS name and version

Windows 64bit

**Comment by smcenlly** [comment] 2021-07-21 03:46
Closing as a duplicate of https://github.com/wallabyjs/quokka/issues/420.

**Closed by smcenlly** 2021-07-21 03:46 UTC
Labels: feature request
