### ISSUE TITLE
VSCode creates a new empty file when I close a quokka file

### ISSUE THREAD

**Issue by fergusmeiklejohn** [wallabyjs/quokka#757] opened 2022-03-11 05:27 UTC
### Issue description or question

When I close a Quokka scratch file and don't save it, it closes properly then VSCode creates a new empty file 

Is this issue related to Quokka not outputting the expected results of your code?: No

### Code editor version

Visual Studio Code v1.65.2
Quokka v1.0.450
### OS name and version

OSX 12.2.1

**Comment by ArtemGovorov** [comment] 2022-03-11 05:46
We can't reproduce the issue, it may be caused by some other extensions that you have installed. Can you please try disabling all other extensions to see if Quokka start working as expected? If so, try bisecting other extensions to find out which one is causing the issue.

**Comment by smcenlly** [comment] 2022-03-13 23:41
Closing this issue as we don't believe it has anything to do with Quokka. Almost certainly a problem with another extension.

**Closed by smcenlly** 2022-03-13 23:41 UTC
Labels: more info is required
