### ISSUE TITLE
Changing Language of scratch file to non-JS format from context menu prevents stop button from working

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/quokka#104] opened 2017-10-23 12:29 UTC
### Issue description or question

See title.

### Sample code

![screen shot 2017-10-23 at 2 27 17 pm](https://user-images.githubusercontent.com/281413/31888955-4af6b910-b7fe-11e7-966b-c12a48785f14.png)

### Code editor version

IntelliJ IDEA 2017.3 EAP (Ultimate Edition)
Build #IU-173.2941.3, built on October 4, 2017
IntelliJ IDEA EAP User
Expiration date: November 2, 2017
JRE: 1.8.0_152-release-1012-b1 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.4

### OS name and version

Windows
**OSX**
Linux

**Comment by ArtemGovorov** [comment] 2017-10-23 12:58
Thanks for the report. The issue is fixed in Quokka plugin v1.0.48.

**Closed** 2017-10-23 12:58 UTC
