### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by PiotrPrzekaza** [wallabyjs/quokka#477] opened 2020-05-11 15:42 UTC
- Issue Type: `Performance`
- Extension Name: `quokka-vscode`
- Extension Version: `1.0.289`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.46.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\piotr\WallabyJs.quokka-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smcenlly** [comment] 2020-05-11 21:43
Could you please attach the file `C:\Users\piotr\WallabyJs.quokka-vscode-unresponsive.cpuprofile.txt` mentioned in your issue comment?

This is likely a duplicate of https://github.com/wallabyjs/quokka/issues/444. From previous issue:

> We can see that the high CPU occurs when unzipping our [interactive examples](https://github.com/wallabyjs/interactive-examples). The high CPU is occurring when trying to close the file handles after the interactive examples have been uncompressed and have been written to disk. During this operation we are writing 519 JavaScript files that are on average 280 bytes in length so this shouldn't be causing a problem.
>
> **The high CPU is likely caused by a virus scanner or system-related operation. A virus scanner is more likely the cause given that these are JavaScript snippets.**

This is a one time operation so it is unlikely you'll see this warning again. If we see that the high CPU is caused by your operating system's file operations then you will need to update your virus scanner to exclude Quokka application folders from being scanner, or else ignore this problem.

**Comment by smcenlly** [comment] 2020-05-12 23:07
Closing this issue as we haven't heard back. As per previous response, this is likely a duplicate of #444 and is caused by your system's virus scanner.

**Closed by smcenlly** 2020-05-12 23:07 UTC
