### ISSUE TITLE
result of Copy Data gives undefined

### ISSUE THREAD

**Issue by dadiborn** [wallabyjs/quokka#482] opened 2020-05-21 22:21 UTC
### Issue description or question
If value is so long that it must be cropped (1) visually in Value Explorer
A: result of Copy Data (3) gives undefined
B: The arrow (2) will appear as it would be array/object.

![quokka_bug2](https://user-images.githubusercontent.com/36768799/82611533-6137cc80-9bc9-11ea-9c93-febeaec684c0.jpg)

### Sample code

```javascript
var logic = '2345678912345678912345678912345678912345678912345678912345678912345678989123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789';
logic;
```
Workaround: to make Copy Value working, to show value instead of undefined, we need to click on that arrow (2) and after that proceed with Copy Data

**Comment by smcenlly** [comment] 2020-05-22 00:38
Thanks for letting us know about this problem. This has been fixed in the latest version of Quokka for IntelliJ, v1.0.233.

Please note that if you copy a truncated string without first expanding, Quokka will now copy the truncated value (instead of undefined); this is by design.

If you would like to automatically expand the value before copying, you may use the live value comment `//?+` which will automatically expand the value for you. For example:

```
var logic = '2345678912345678912345678912345678912345678912345678912345678912345678989123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789';
logic; //?+
```

**Closed by smcenlly** 2020-05-22 00:38 UTC
