### ISSUE TITLE
Autorun configuration is unable to recover after invalid config error

### ISSUE THREAD

**Issue by Alexsey** [wallabyjs/quokka#418] opened 2019-09-21 12:13 UTC
### Issue description or question

If the inline config has been set unproperly and then been fixed, Quokka would continue to show old error

### Sample code

```javascript
({x: 1})

'a', 'b'
```
This would give an error "Cannot read property 'javascript' of undefined"

Now delete the first line - the error is still there

### Quokka.js Console Output

```
Quokka #1 (node: v12.10.0)

Cannot read property 'javascript' of undefined
```

### Code editor version

Webstorm v2019.3 EAP#2

### OS name and version

Windows 10 Pro

**Comment by smcenlly** [comment] 2019-09-23 00:03
This is a duplicate of #417. The configuration would not work in either case.

**Closed by smcenlly** 2019-09-23 00:03 UTC
