### ISSUE TITLE
Intellij Issue

### ISSUE THREAD

**Issue by rtigrett** [wallabyjs/quokka#351] opened 2019-04-09 18:23 UTC
Intellij plugin error popup,

java.lang.IllegalArgumentException: Argument for @NotNull parameter 'component' of com/intellij/util/ui/UIUtil.isFocusAncestor must not be null
	at com.intellij.util.ui.UIUtil.$$$reportNull$$$0(UIUtil.java)
	at com.intellij.util.ui.UIUtil.isFocusAncestor(UIUtil.java)
	at com.intellij.ui.content.impl.ContentManagerImpl.removeContent(ContentManagerImpl.java:164)
	at com.quokka.javascript.QuokkaView.a(Unknown Source)
	at com.quokka.javascript.session.p.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:747)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:696)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by smcenlly** [comment] 2019-04-09 23:18
We addressed an issue 14 days ago that was caused by a breaking change in the latest IntelliJ editors that we believe is the same problem that you have reported. The problem is addressed in Quokka-IntelliJ plugin versions after 1.0.151.

If you are already using a Quokka-IntelliJ plugin version greater than 1.0.151, could you please provide us with the following additional information?

1) What is your Quokka plugin version?
2) What IntelliJ editor are using?
3) What is the IntelliJ editor version?
4) Does the error happen immediately? If not, what steps do you take before it occurs?

**Comment by smcenlly** [comment] 2019-04-11 23:01
@rtigrett - I'm closing this issue as we haven't heard back from you and are expecting the latest version of the IntelliJ plugin to fix your problem. If you still have the issue with the latest version, please let us know and provide us with the additional information we requested and we'll re-open.

**Closed by smcenlly** 2019-04-11 23:01 UTC
