### ISSUE TITLE
Getters are not getting resolved

### ISSUE THREAD

**Issue by Alexsey** [wallabyjs/quokka#421] opened 2019-09-26 16:51 UTC
### Issue description or question

Only Value Explorer can resolve getters, although requires explicit click on getter key in the object tree

If it's not by design - it would be nice if getters would always be resolved automatically

If it's by design - then resolve them only for Live Comments with `+` like `//?+`/`/*?+*/` and for Copy/Show Value actions

In any case, after a getter has been explicitly resolved in Value Explorer there is no reason not to show it's value in Live Comments and Quokka console

### Sample code

```javascript
const {inspect} = require('util')

const o = {
  x: 1,
  get y() {return this.x + 2}
}

o //?+
o //? inspect($, {getters: true})
```

### Quokka.js Console Output

```
Quokka #1 (node: v12.10.0)

{ x: 1, y: [Getter] }
	at o _.js:8:0

{ x: 1, y: [Getter: 3] }
	at inspect($, {getters: true}) _.js:9:0
```

![quokkaGetters](https://user-images.githubusercontent.com/6392013/65708296-eb5d7e80-e096-11e9-8ec1-da482308fb6f.png)

### Code editor version

Webstorm v2019.2.3

### OS name and version

Windows 10 Pro

**Comment by smcenlly** [comment] 2019-09-26 22:30
This is by design as Quokka getters contain executable code, and executing them may change the execution outcome of your code. I'm marking this as a feature request for us to evaluate how to do this safely (we may need to include some additional comment hints).

**Comment by smcenlly** [comment] 2022-06-16 02:36
Quokka has a new setting to change the default behavior of not resolving getters. In the latest version of Quokka, you may now set `resolveGetters` to `true` in your Quokka configuration.

```json
{
  "resolveGetters": true
}
```

**Closed by smcenlly** 2022-06-16 02:36 UTC
Labels: feature request
