### ISSUE TITLE
Can not start node.js process (node), make sure your system has node.js installed

### ISSUE THREAD

**Issue by ghost** [wallabyjs/quokka#1] opened 2017-03-15 13:39 UTC
### Issue description or question

Can't start quokka at all.
Error: Can not start node.js process (node), make sure your system has node.js installed.

### Code editor version

Version 1.10.2 (1.10.2)
Node version 7.7.1 via NVM

### OS name and version

OSX

**Comment by ArtemGovorov** [comment] 2017-03-15 13:44
At the moment quokka just runs `node` command, that doesn't seem to be available in your case. You may specify the absolute path to the desirable node executable via VS Code `settings.json` `quokka.node` setting:
<img width="888" alt="screen shot 2017-03-15 at 11 42 43 pm" src="https://cloud.githubusercontent.com/assets/979966/23951175/25b1ae7c-09d9-11e7-8835-6b9e719c2980.png">

**Comment by leRenart** [comment] 2017-03-15 13:57
Still No luck

with `"quokka.node": "~/.nvm/versions/node/v7.7.1/bin/node"`

I get "Can not start node.js process (~/.nvm/versions/node/v7.7.1/bin/node), make sure your system has node.js installed."

Just checked and that's the right path to the executable

**Comment by ArtemGovorov** [comment] 2017-03-15 13:59
Hmm, strange. Try an absolute path without the `~`.

**Comment by leRenart** [comment] 2017-03-15 14:02
"Can not start node.js process (/Users/xxxxxx/.nvm/versions/node/v7.7.1/bin/node), make sure your system has node.js installed."

**Comment by ArtemGovorov** [comment] 2017-03-15 14:14
Quokka is spawning a new node process like this: 

```
require('child_process').spawn('node')
```
or like this if you specify the `quokka.node` setting:
```
require('child_process').spawn('/Users/xxxxxx/.nvm/versions/node/v7.7.1/bin/node')
```
Please double check the path. Also try a small node program that just has the line above to see if it's  throwing the `spawn ... ENOENT` exception.

**Comment by leRenart** [comment] 2017-03-15 14:19
No exceptions so far, I can see two node process

**Comment by reflog** [comment] 2017-03-15 14:28
same here, but on windows, and with regular install. #2

**Comment by ArtemGovorov** [comment] 2017-03-15 14:30
Are you starting quokka with some project opened or without any project?

**Comment by leRenart** [comment] 2017-03-15 14:31
I can confirm, it seems to work if you are in a project.

**Comment by reflog** [comment] 2017-03-15 14:34
@ArtemGovorov - without a project.

**Comment by ArtemGovorov** [comment] 2017-03-15 14:34
Ok, cool, try opening it in some project/folder, running it, then you can close it, and start it without a project. We'll be fixing it shortly.

**Comment by reflog** [comment] 2017-03-15 14:35
Awesome. Thank you!

**Comment by ArtemGovorov** [comment] 2017-03-15 14:43
The issue is fixed and the fix is published in v1.0.5.

**Comment by sirigull** [comment] 2017-10-17 19:52
Still an issue.

**Comment by ArtemGovorov** [comment] 2017-10-17 21:55
@sirigull Did you specify your node version path as [described here in the docs](https://quokkajs.com/docs/configuration.html#nodejs-version)? If yes, then please double check the path. If you reckon the path is correct but it's still not working, please share your quokka config with the path you are trying to set.

**Comment by ChaossAdept7** [comment] 2018-10-27 12:06
I see that issue on linux mint on WebStorm(2018.2). Node is installed, nvm is installed, I've tried to set config.json file(absolute path also does not work) like in description. Version of quokka plugin - 1.0.121
```
{
	"node": "~/.nvm/versions/node/v9.11.2/bin/node"
}
```

**Comment by ChaossAdept7** [comment] 2018-10-28 14:11
I don't know what from instructions You sent did the trick - but now it works, thanks!

**Comment by davve14** [comment] 2019-03-22 09:21
same problem for me, only running node should work for me but it doesn't.
Linux, running Visual Studio Code

**Comment by ArtemGovorov** [comment] 2019-03-22 12:15
@davve14 Have you tried:
- specifying node executable path: https://github.com/wallabyjs/quokka/issues/1#issuecomment-286745060 in your settings?
- adding `"stdEsm": false` to your [Quokka config](https://quokkajs.com/docs/configuration.html)  to see if it changes anything?

**Comment by davve14** [comment] 2019-03-22 13:36
{
        "pro":false,
        "node": "/usr/bin/node",
        "stdEsm": false
}

This is what I am trying, simply node also works for this user so not sure why this would be needed, I guess there is something else I am doing wrong.

**Comment by smcenlly** [comment] 2019-03-22 22:32
Can you please confirm that typing `/usr/bin/node` works from your terminal? If that doesn't work, then the path must be wrong.

Can you also confirm that the path you're using is the same that gets returned if you run `which node` from your terminal?

**Comment by davve14** [comment] 2019-03-24 09:05
yes, /usr/bin/node -v
v10.15.0
which node
/usr/bin/node

**Comment by ArtemGovorov** [comment] 2019-03-24 10:30
@davve14 Could you please 
- paste the exact error message you're getting?
- check if `/usr/bin/node` is node executable or a symlink?

**Comment by davve14** [comment] 2019-03-24 10:44
I do ctrl+shift+p, Choose new Javascript file:
You may use the "node" setting to configure the location of node.
Can not start node.js process(/usr/bin/node) make sure your system has node.js installed.

ls -ltr node
-rwxr-xr-x. 1 root root 31711088 Jan  2 22:22 node

**Comment by ArtemGovorov** [comment] 2019-03-25 00:57
@davve14 Thanks. Try the latest version on the plugin v1.0.198 to see if it helps.

**Comment by davve14** [comment] 2019-03-26 17:58
No, that doesnt help either.

**Comment by smcenlly** [comment] 2019-03-26 23:38
Could you please provide us with two things:

1. Any details logged in your Quokka output window, which should be something like this:

```
​​​​Quokka​​​​
Error: spawn /usr/bin/node ENOENT 
	at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19) 
	at onErrorNT (internal/child_process.js:406:16) 
	at process._tickCallback (internal/process/next_tick.js:63:19) 
```

2. Could you please try setting a VSCode user setting, "quokka.node" to the same path that you have referenced in your quokka `config.json` file?

**Comment by davve14** [comment] 2019-03-31 09:29
hmm, cannot find any such output.
put quokka.node in settings.json, it says "unknown configuration" but I think it should be the right place.

**Comment by Darksoulsong** [comment] 2019-04-01 18:48
@davve14  I second this. "quokka.node" in settings.json is deemed as "unknown configuration setting" by vscode.

**Comment by Darksoulsong** [comment] 2019-04-01 18:53
`$ /usr/local/bin/node --version` gives me the node version, so it's the right path; but I'm still getting the "Can not start node.js process (/usr/local/bin/node), make sure your system has node.js installed."

**Comment by smcenlly** [comment] 2019-04-01 23:06
You can ignore the `Unknown configuration setting` warning. This is a hidden setting, but will still be picked up by Quokka at runtime.

Regarding the output, I've provided a screenshot below that shows where you can find the Quokka output:

![image](https://user-images.githubusercontent.com/2074089/55365068-744f8f00-5526-11e9-8993-dcc1f3a63599.png)

Can you please provide us with a screenshot of the message that you're receiving if it's not from the Quokka output?

**Comment by Darksoulsong** [comment] 2019-04-02 16:56
I solved my issue by reinstalling vscode. After that, quokka is able to reach the node executable.

**Comment by smcenlly** [comment] 2019-04-02 22:28
Thanks for letting us know. We'd not seen that before.

**Comment by davve14** [comment] 2019-04-06 08:24
hi again, I found out that I was running the flatpak version, I tried the "real" version at it works fine, so I am fine, is the permissions for the flatpak app setup in such a way that that is out of the question? Have you tested it?

**Comment by smcenlly** [comment] 2019-04-09 23:44
We haven't tested with flatpak. In fact, I wasn't aware of flatpak until you mentioned it. We've done a bit of research and taken a look at the VS Code flatpak build. Along the way, we found [this warning file](https://github.com/flathub/com.visualstudio.code/blob/master/flatpak-warning.txt), with the following message:

```
------------------------------------------------------------------------------------
| Warning: You are running an unofficial Flatpak version of Visual Studio Code !!! |
------------------------------------------------------------------------------------
...
This version is running inside a container and is therefore not able
to access SDKs on your host system!
...
```

I would say that your problem is VS Code is running inside a container without access to your local system node versions, etc.

Please also note: we only support Microsoft's official VS Code distros.

**Comment by jordanpapaleo** [comment] 2019-07-31 23:13
fwiw: I encountered this issue after changing my default version used by nvm.  I tried disabling and re-enabling, uninstalling and reinstalling. None of that worked.  I followed the above instructions where I updated  Visual Code's `settings.json` by adding a key of`"quokka.node"` and a value of my absolute node path.  I can confirm this key does make a warning about `Unknown configuration setting` and that it still works like @ArtemGovorov said.  The easiest way to get the absolute path is to type `which node` in your terminal.

For Example:

![image](https://user-images.githubusercontent.com/1728807/62254219-37e55000-b3ad-11e9-8638-414cd2bed91c.png)

![image](https://user-images.githubusercontent.com/1728807/62254300-7844ce00-b3ad-11e9-8b91-71fa2210fc7f.png)

**Comment by smcenlly** [comment] 2019-07-31 23:47
We're not sure why you had this issue. If you don't specify a node path, we simply use `node` executable and let your ambient path settings resolve your executable. Did you log out/log back in after changing the path/uninstalling/etc? At any rate, I don't believe it's a Quokka issue, and you should be able to duplicate in any VS Code extension simply by using:

```javascript
require('child_process').spawn('node', ['--version']);
```

I did a quick google search for `VSCode can't find node` and it looks like other people have had similar problems (not using Quokka).

**One thing I would like to note** is that while we support "quokka.node" VS Code setting, the preferred method for specifying the node version is to update your [global Quokka configuration](https://quokkajs.com/docs/configuration.html#global-config-file) and add:

```javascript
{
...
    "node": "/Users/username/.nvm/versions/node/v7.7.1/bin/node"
...
}
```

**Comment by jordanpapaleo** [comment] 2019-07-31 23:59
HI - I am sure where the issues lies at all, but I suspect you are correct it is a VSCode issue.  I just wanted to share how the conversation in this issue helped me as the VSCode information in the error sent me to a Quokka url.

**Comment by SimoSultan** [comment] 2020-08-24 06:26
hi, I can't run this extension either.

which node = /usr/bin/node
node version = v12.18.3

these are the things I have tried in the quokka settings file
`{
  "pro":false,
  "node": "/usr/bin/node"  
  // "node": "/Users/simon/.nvm/versions/node/v12.18.3/bin/node",
  // "node": "~/.nvm/current/bin/node",
  // "stdEsm": false
}`

I have tried this in the vscode settings.json

`    // "quokka.node": "/usr/bin/node",
    // "quokka.node": "/Users/simon/.nvm/versions/node/v12.18.3/bin/node",
    // "quokka.node": "~/.nvm/current/bin/node",
`

and these are the errors I get when I have `"node": "usr/bin/node"` uncommented in the quokka settings.json

>You may use the "node" setting to configure the location of node.
> Can not start node.js process (node), make sure your system has node.js installed.
> Looks like your quokka config.json file has invalid syntax, it should be a valid JSON file.

**Comment by ArtemGovorov** [comment] 2020-08-24 07:00
@SimoSultan 
As the warning message states, your Quokka `config.json` is not a valid JSON file (JSON can't have comments). Try this `config.json`:

```json
{
  "pro":false,
  "node": "/Users/simon/.nvm/versions/node/v12.18.3/bin/node"
}
```

(and make sure `/Users/simon/.nvm/versions/node/v12.18.3/bin/node` exists).

**Comment by SimoSultan** [comment] 2020-08-24 07:09
Ah right didn't know I couldn't have comments in there.
but it still doesn't work. the syntax error has gone but it stil; shows that it cannot start the process

I don't have a versions folder in the .nvm folder, only .git, .github and .test
which is why I was trying usr/bin/node as that's what 'which' spits out

Is there something else I am doing wrong @ArtemGovorov?

**Comment by ArtemGovorov** [comment] 2020-08-24 07:43
@SimoSultan 
> I am using WSL 18.04

In this case please follow these instructions in our docs: https://quokkajs.com/docs/configuration.html#windows-subsystem-for-linux-wsl

**Comment by SimoSultan** [comment] 2020-08-24 08:06
thanks @ArtemGovorov I got it working with:

`{
  "useWsl": true,
  "pro":false,
  "node": "/usr/bin/node"
}`

I didn't notice the WSL part sorry.

**Comment by akarpov91** [comment] 2021-03-14 22:27
Hi I'm also getting the following error:

`Can not start node.js process (/Users/alex91/opt/homebrew/bin/node), make sure your system has node.js installed.`

Device: MacBook Air M1 Chip
Node Version: v15.11.0

.quokka/config.json
`{
  "pro": false,
  "node": "~/opt/homebrew/bin/node",
  "recycle": true,
  "stdEsm": false,
  "nativeEsm": true
}`

settings.json
`{"quokka.node": "~/opt/homebrew/bin/node"}`

**Comment by smcenlly** [comment] 2021-03-14 23:36
@akarpov91 - it looks like there's an issue in your path. From the terminal if you run `~/opt/homebrew/bin/node --version` does it work for you? It looks like you need to remove the `~` character from the start of your path.

**Comment by akarpov91** [comment] 2021-03-15 00:52
Thanks @smcenlly that worked. 

However, I get the following new error now in output:

`​​​​​Quokka 'quokka.js' (node: v15.11.0)​​​​ ​View recent Quokka files​
(node:28951) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time 
(Use `node --trace-warnings ...` to show where the warning was created) `

**Comment by smcenlly** [comment] 2021-03-15 01:16
Are you getting an error or just a warning in your Quokka console? Could you please provide us with a screenshot of your code + the Quokka console?

**Comment by akarpov91** [comment] 2021-03-15 01:23
@smcenlly see below image. 

<img width="954" alt="Screen Shot 2021-03-14 at 8 21 07 PM" src="https://user-images.githubusercontent.com/20190435/111092031-d848a380-8502-11eb-9cbe-cc94ee06b65a.png">

**Comment by smcenlly** [comment] 2021-03-15 21:45
Could you please see if there are any errors reported in the VS Code Developer Console (run the command `Developer: Toggle Developer Tools` and inspect the console output).

**Comment by akarpov91** [comment] 2021-03-15 22:34
@smcenlly please see below: 

<img width="541" alt="Screen Shot 2021-03-15 at 5 34 03 PM" src="https://user-images.githubusercontent.com/20190435/111229852-a728ab80-85b4-11eb-9b68-9a1d25e7ba2d.png">

**Comment by smcenlly** [comment] 2021-03-16 01:17
Could you please provide the full console log (it appears to be truncated).

Thanks

**Comment by akarpov91** [comment] 2021-03-16 17:25
@smcenlly below is the full console log:

`[Extension Host]  Quokka.js Live Share integration disabled, VSLS not found.
/private/var/folders…desktop.main.js:626   ERR read ENOTCONN: Error: read ENOTCONN
    at tryReadStart (net.js:573:20)
    at Socket._read (net.js:584:5)
    at Socket.Readable.read (_stream_readable.js:467:10)
    at Socket.read (net.js:624:39)
    at new Socket (net.js:376:12)
    at Object.Socket (net.js:267:41)
    at createSocket (internal/child_process.js:314:14)
    at ChildProcess.spawn (internal/child_process.js:437:23)
    at Object.spawn (child_process.js:557:9)
    at t.Git.spawn (/private/var/folders/n5/cjckmm0x5nvcjp_j6534m0000000gn/T/AppTranslocation/93514210-2564-4BDA-83F1-EB8EE12D9913/d/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:1:89325)
    at t.Git._exec (/private/var/folders/n5/cjckmm0x5nvcjp_j6534m0000000gn/T/AppTranslocation/93514210-2564-4BDA-83F1-EB8EE12D9913/d/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:1:88493)
    at t.Git.exec (/private/var/folders/n5/cjckmm0x5nvcjp_j6534m0000000gn/T/AppTranslocation/93514210-2564-4BDA-83F1-EB8EE12D9913/d/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:1:88334)
    at t.Git.getRepositoryRoot (/private/var/folders/n5/cjckmm0x5nvcjp_j6534m0000000gn/T/AppTranslocation/93514210-2564-4BDA-83F1-EB8EE12D9913/d/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:1:87583)
    at g.openRepository (/private/var/folders/n5/cjckmm0x5nvcjp_j6534m0000000gn/T/AppTranslocation/93514210-2564-4BDA-83F1-EB8EE12D9913/d/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:10:406906)
    at n (/private/var/folders/n5/cjckmm0x5nvcjp_j6534m0000000gn/T/AppTranslocation/93514210-2564-4BDA-83F1-EB8EE12D9913/d/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:1:24339)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
/private/var/folders….desktop.main.js:62 [Extension Host]  [Info]  #index.js Quokka.js started
/private/var/folders….desktop.main.js:62 [Extension Host]  [Error] #index.js (node:29762) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
/private/var/folders….desktop.main.js:62 [Extension Host]  [Error] #index.js (Use `node --trace-warnings ...` to show where the warning was created)
/private/var/folders….desktop.main.js:62 [Extension Host]  [Error] #index.js (node:29763) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
/private/var/folders….desktop.main.js:62 [Extension Host]  [Error] #index.js (Use `node --trace-warnings ...` to show where the warning was created)
/private/var/folders….desktop.main.js:62 [Extension Host]  [Error] #index.js (node:29764) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
/private/var/folders….desktop.main.js:62 [Extension Host]  [Error] #index.js (Use `node --trace-warnings ...` to show where the warning was created)
/private/var/folders….desktop.main.js:62 [Extension Host]  [Error] #index.js (node:29765) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
/private/var/folders….desktop.main.js:62 [Extension Host]  [Error] #index.js (Use `node --trace-warnings ...` to show where the warning was created)
/private/var/folders….desktop.main.js:62 [Extension Host]  [Info]  #index.js Quokka.js stopped
/private/var/folders….desktop.main.js:62 [Extension Host]  [Info]  #index.js Quokka.js started
/private/var/folders….desktop.main.js:62 [Extension Host]  [Error] #index.js (node:30513) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
/private/var/folders….desktop.main.js:62 [Extension Host]  [Error] #index.js (Use `node --trace-warnings ...` to show where the warning was created)
/private/var/folders….desktop.main.js:62 [Extension Host]  [Error] #index.js (node:30514) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
/private/var/folders….desktop.main.js:62 [Extension Host]  [Error] #index.js (Use `node --trace-warnings ...` to show where the warning was created)
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/f30a9b7…/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout
﻿
​`

**Comment by smcenlly** [comment] 2021-03-17 02:39
@akarpov91 - thanks for providing the log. We've fixed the problem in the latest version of Quokka, (VS Code v1.0.350). Please update to the latest version and it should work for you.

**Comment by akarpov91** [comment] 2021-03-17 21:26
Thanks @smcenlly I'm now able to see the output in the 'OUTPUT' tab of vscode. 

Is there something I need to set see the 'Live Execution and Results'?

**Comment by smcenlly** [comment] 2021-03-17 22:08
It sounds like you may be trying to use some 'PRO' features. You can read about the differences between Community and PRO on our [comparison page](https://quokkajs.com/pro/). If you want to try PRO features, you may [request a trial license](https://quokkajs.com/pro/#try-pro-free).

**Comment by akarpov91** [comment] 2021-03-17 22:44
@smcenlly the 'Live Results' seem to be part of the 'Community Edition' but are not showing up for me.

**Comment by smcenlly** [comment] 2021-03-17 22:59
Can you please provide an example of your code that's not working for you?

**Comment by akarpov91** [comment] 2021-03-17 23:31
@smcenlly see below, the output is not showing up inline

<img width="750" alt="Screen Shot 2021-03-17 at 6 27 35 PM" src="https://user-images.githubusercontent.com/20190435/111551564-78ded380-874e-11eb-9ce6-084d5bf632a7.png">

**Comment by smcenlly** [comment] 2021-03-17 23:48
@akarpov91 - I think I understand what is going on. You are attempting to run a `nativeEsm` file with a `.js` extension and either your root folder is missing a `package.json` file OR your `package.json` `type` setting is missing or is `commonjs`.

For Quokka (and node) to correctly process your file using `nativeEsm`, your file extension must be `.mjs` unless your have a `package.json` with the `type` set to `module`. Since your file extension is incorrect some things (including coverage) will not work for you.

Out of interest, is there a reason that you are using:
* `recycle`: true,
* `stdEsm`: false, and
* `nativeEsm`: true?

If not, it would be better to remove these settings from your `config.json`.

**Comment by akarpov91** [comment] 2021-03-18 00:46
@smcenlly removing those fields from `config.json` fixed it. 

Thanks so much for your help here.

**Closed** 2021-04-14 03:41 UTC

**Comment by xXMarcinatorXx** [comment] 2021-04-21 17:37
I also have this issue and after reading this i haven't found a solution to the same problem on my pc. 

NVM version: 1.1.7
node version: v14.8.0
npm version: 6.14.7
Operating system: windows

Quokka global config
{"node": "C:/Users/user/AppData/Roaming/nvm/v14.8.0", "pro": false, "community": true, "debug": true}

Image of the directory
![image](https://user-images.githubusercontent.com/25668644/115596440-64a36e80-a2d8-11eb-8a67-5d2344a97ddf.png)

Error in VSCode
![image](https://user-images.githubusercontent.com/25668644/115596532-800e7980-a2d8-11eb-99d7-e520bb2e07ff.png)

Developer console output
![image](https://user-images.githubusercontent.com/25668644/115596870-e3001080-a2d8-11eb-869e-0349a8b5790f.png)

I can run node applications just fine of use the normal nodejs command line tools.

Any idea Why. Thanks in advance.

**Comment by smcenlly** [comment] 2021-04-21 21:54
It looks like the `node` path in your Global Quokka configuration is incorrect. Because you are using Windows, you will need to ensure that the path separator is the Windows path separator (`\`) and not the Unix path separator (`/`).

Assuming that you copy-pasted your Quokka `config.json` and the v14.8.0 directory exists, the following should work for you:

**Updated config.json**
```json
{
  "node": "C:\\Users\\user\\AppData\\Roaming\\nvm\\v14.8.0\\node.exe", 
  "pro": false
}
```

**Comment by xXMarcinatorXx** [comment] 2021-04-22 15:08
Thanks for that it worked. But it seems that the real issue was that I was missing the "\\node.exe" at the end because I tried for good measure to use the `/` instead of `\` and it seems to work fine.

**Comment by Obada-gh** [comment] 2021-11-29 17:20
> ### Issue description or question
> Can't start quokka at all. Error: Can not start node.js process (node), make sure your system has node.js installed.
> 
> ### Code editor version
> Version 1.10.2 (1.10.2) Node version 7.7.1 via NVM
> 
> ### OS name and version
> OSX

Try to download the node from the official site or reinstall the nvm

**Comment by smcenlly** [comment] 2021-11-29 22:33
@Obada-gh - if I have understood your comment correctly, you are using `node` version 7.7.1. Unfortunately Quokka does not support `node` version `7.x`. Version 7 was declared end of life was declared `2017-06-30` by Node.js Working Group and is no longer supported by many tools (including Quokka).

Please [update to a later version of node](https://nodejs.org/en/) (we recommend latest LTS) and Quokka should work for you.

If you are still having problems, please [explicitly define where to load `node`](https://quokkajs.com/docs/configuration.html#nodejs-version) from in your [global `config.json`](https://quokkajs.com/docs/configuration.html#global-config-file) as [mentioned above](https://github.com/wallabyjs/quokka/issues/1#issuecomment-824383698).

**Comment by Obada-gh** [comment] 2021-11-30 09:08
@smcenlly I was have the same problem with the new node version but I reinstall it from the official site and its working fine now.

**Comment by techstackmedia** [comment] 2022-01-08 16:23
- In terminal type `which node`
- copy the path somewhere
- Also in your terminal type the code `open .quokka`
- drag the config.json file to vs code
- edit the file such that `{..., "node": "paste the returned path of 'which node' here" }`

**Comment by lloydbanks** [comment] 2022-01-18 01:11
I believe this thread should not be closed since the issue is still not resolved due to regular comments.
I have the latest quokka version and I get this error
`Can not start node.js process (C:\Users\user\AppData\Roaming\npm\node)`
Here's my Windows config 
```
{
	"pro": false,
	"node": "C:\\Users\\user\\AppData\\Roaming\\npm\\node"
}
```
I don't understand why I have to manually modify `config.json` to specify `node` path, wtf? The node is already installed and path is already correct, so why it doesn't work initially?

And there's also another error:
`runnerw.exe: CreateProcess failed with error 193: %1 is not a valid Win32 application.`

I didn't make any customizations, I've just installed the plugin and it doesn't work.

**Comment by smcenlly** [comment] 2022-01-18 01:33
@lloydbanks - `node.js` is a pre-requisite for Quokka and must be installed correctly on your system and available in your system path in order for Quokka to operate correctly. This is not actually a problem with Quokka and unfortunately there is not a lot we can do in our product to fix this for you.

If you have just installed node.js, you may need to reboot before node is available in your system path.

If you start the command prompt, does `node --version` work for you? If it does not, this means that node is missing from your user/system path.

I have node installed on my Windows machine and there is no `%AppData%\npm\node.exe` executable in that location.

You may determine where node is located by using the command prompt and typing `where node`. On my machine it is located in `C:\Program Files\nodejs\node.exe`.

[This video](https://www.youtube.com/watch?v=oFF_QryVSJk) may assist you in adding node to your paths (again, please note that you may need to reboot before they change takes effect in your editor).

**Comment by lloydbanks** [comment] 2022-01-18 01:37
@smcenlly thanks for your reply. 
As I said before, I have no problems with `node.js`, it's already installed correctly and the path is correct.
`node --version` returns `v14.17.6`

**Comment by ArtemGovorov** [comment] 2022-01-18 04:56
@lloydbanks 
Thanks for providing the requested details. Can you please try this in your Quokka config.json:
```
{
	"pro": false,
	"node": "C:\\Program Files\\nodejs\\node.exe"
}
```
(note that you need to start a new Quokka file or restart it on the existing file for the node setting change to take effect).

The issue seem to be related to the way WebStorm reads your node location (when asked by Quokka plugin to do so), and it may be related to various things specific to your environment. Once we you have the working `config.json` that makes the tool work, we can continue to investigate the specific issue. To assist with it, please create a separate issue and attach your IDEA.log file (in Webstorm it's accessible via `Help - Show log...`).

**Comment by lloydbanks** [comment] 2022-01-18 16:39
@ArtemGovorov 
`"node": "C:\\Program Files\\nodejs\\node.exe"`
Yes, this line finally worked for me after I reinstalled Webstorm and Quokka. Idk how to explain this magic.

I really appreciate, that you continued to investigate my issue, so I remove my negative review. Sorry if it was offensive or too emotional.

I will take time and better learn this tool. 
Anyway, thanks for your help.

**Comment by ArtemGovorov** [comment] 2022-01-18 23:38
@lloydbanks Appreciate your patience. For some reason the plugin (or Webstorm) seems to fail to determine your installed node location (via system path), so that's why the config entry is required. Glad to hear the config setting gets the job done for your case.

**Comment by egomezc19** [comment] 2022-06-13 22:47
Estuve batallando con este error que me desplegaba VSCODE
1. Can not start node.js process (node), make sure your system has node.js installed.

2. spawn node ENOENT

3. You may use the "node" setting to configure the location of node.

y encontre esta solucion, Cierren todos sus espacios de trabajos, cierran VSCODE y lo vuelven abrir, luego ya mandan a llamar a quokka.js Start on current file y listo, si no realicen lo siguiente...


Haga clic enFile / Close workspace
Todos tus proyectos están cerrados.
Algunas extensiones se actualizan y de repente abren ventanas que dicen "Novedades"
Abra un proyecto (en el "Espacio de trabajo sin título" que se ha creado de forma predeterminada)
Intente ejecutar Quokka nuevamente, funcionó para mí
