### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by gyanendra2058** [wallabyjs/quokka#684] opened 2021-09-22 11:02 UTC
- Issue Type: `Performance`
- Extension Name: `quokka-vscode`
- Extension Version: `1.0.401`
- OS Version: `Darwin x64 19.6.0`
- VS Code version: `1.56.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/w5/pc7wz4mn4bsdw4r6s9c8vkvm0000gn/T/WallabyJs.quokka-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by gyanendra2058** [comment] 2021-09-22 11:06
[WallabyJs.quokka-vscode-unresponsive.cpuprofile.txt](https://github.com/wallabyjs/quokka/files/7210113/WallabyJs.quokka-vscode-unresponsive.cpuprofile.txt)

**Comment by smcenlly** [comment] 2021-09-22 23:41
Thanks for your report and for providing the CPU profile.

This is likely a duplicate of #444.

We can see that the high CPU occurs when reading a file from disk. The high CPU is likely caused by a virus scanner or system-related operation. We expect this is a one time operation so it is unlikely you'll see this warning again. If you have the problem again, please try to exclude Quokka application folders from being scanned by your virus scanner.

For now, we will close this ticket as we don't believe this is related to Quokka. If you continue to get high CPU warnings, please reply to this ticket and we will reopen it. Please also describe what you are doing when you get high CPU.

**Closed by smcenlly** 2021-09-22 23:41 UTC
