### ISSUE TITLE
console input 

### ISSUE THREAD

**Issue by hamidrezarat** [wallabyjs/quokka#626] opened 2021-05-06 20:17 UTC
Is there a way to have a console input in Quokka ?
I mean something like the prompt function in the browser .

I think this option is really needed.

**Comment by smcenlly** [comment] 2021-05-06 22:07
Closing as a duplicate of https://github.com/wallabyjs/quokka/issues/538

**Closed by smcenlly** 2021-05-06 22:07 UTC

**Comment by deniercounter** [comment] 2022-01-21 11:48
@smcenlly Unfortunately your duplicate is a recursion to a closed issue. 

Is there a way to receive values from a terminal and rerun the “quokka” monitored code of the JS-file based on a watched new received value?

**Comment by smcenlly** [comment] 2022-01-21 22:31
@deniercounter - I don't understand your comment. The duplication mentioned above is still open...

There is no way for Quokka to receive values from the terminal.

**Comment by deniercounter** [comment] 2022-01-22 11:02
@smcenlly : Thanks, your fast answer saved time
