### ISSUE TITLE
Using ES6 module syntax without babel breaks code coverage coloring

### ISSUE THREAD

**Issue by EdonGashi** [wallabyjs/quokka#162] opened 2018-02-24 01:06 UTC
### Issue description or question

Using ES6 module syntax without babel breaks code coverage coloring.

When import/export syntax is involved it looks like some inter-process proxying happens. Maybe that causes loss of error stack traces.

### Sample code

Without ES6 modules
![image](https://user-images.githubusercontent.com/12145268/36623569-2b692bdc-1906-11e8-8a63-f90ce6a236c1.png)

With ES6 modules
![image](https://user-images.githubusercontent.com/12145268/36623596-5ff18160-1906-11e8-9a52-8abeb68ddbd1.png)

### Quokka.js Console Output

Included in screenshots above

### Code editor version

Visual Studio Code
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

### OS name and version

Windows 10 x64

**Comment by ArtemGovorov** [comment] 2018-02-24 04:48
Thanks for the report, the issue is fixed in the latest published extension v1.0.106.

**Closed by ArtemGovorov** 2018-02-24 04:48 UTC
