### ISSUE TITLE
Live Share not working

### ISSUE THREAD

**Issue by groinder** [wallabyjs/quokka#468] opened 2020-03-19 13:06 UTC
### Issue description or question

Quokka doesn't work on the client during Live Share session.
I've allowed Quokka to run during Live Share session and it shows results on host just fine, but none are shown to the participants (Quokka extension installed there as well). 

### Code editor version

Visual Studio Code v1.43.1

### OS name and version

Testes on latest Windows and OSX.

**Comment by smcenlly** [comment] 2020-03-19 22:27
Thanks for reporting the problem. 

We assume that you're having problems when you're attempting to run on an unsaved file or a new quokka file?

When we first implemented our LiveShare support, it was not possible to share new files that weren't committed to disk during a live share session. It looks like this is now possible and isn't supported by Quokka. 

We confirmed that Quokka works when starting on a file that already exists on disk. If this isn't working for you, can you please provide us with step-by-step details of what you are doing and what's not working. In the meantime, we'll investigate whether can can support running Quokka on files that don't exist on disk.

**Comment by smcenlly** [comment] 2020-03-20 04:42
We have just added support for unsaved files for Quokka and live share. This is available in the latest version, v1.0.284.

We also made a few other tweaks and improvements at the same time. Please try the latest version and if you're still having the same problem, let us know and we'll re-open the issue.

**Closed by smcenlly** 2020-03-20 04:42 UTC

**Comment by groinder** [comment] 2020-03-30 09:50
@smcenlly Thanks for the answers. I can confirm that the newest version (v1.0.284) works for new files created during live share session, until saved. Quokka doesn't run now at all during live share session for files saved to disk. When I issue `Start on current file` nothing happens.

**Comment by smcenlly** [comment] 2020-03-30 23:01
@groinder - this is working for us (see gif below):

![live_share_existing_file](https://user-images.githubusercontent.com/2074089/77969825-08b52300-732e-11ea-8b6e-06463103ede6.gif)

Is it possible that you are trying to start Quokka on a file that is outside of your project folder/workspace?
