### ISSUE TITLE
Sending HTTPS request with axios in quokka.js

### ISSUE THREAD

**Issue by dropyourcoffee** [wallabyjs/quokka#469] opened 2020-03-25 19:33 UTC
I am trying to configure an run-time quokka.js environment to debug react-hook.

My quokka config in package.json is :
```javascript
  "quokka": {
    "babel": true,
    "plugins": [
      "./handle_tls_reject_unauthorized",  // --> setup globals before initializing jsdom-quokka-plugin
      "jsdom-quokka-plugin",
      "./quokka_mutation_shim".  // --> Setting up MutationObserver (this is fine.)
    ],
    "env": {
      "params": {
        "env": "NODE_ENV=development"
      }
    }
  },
```

In `handle_tls_reject_unauthorized.js` I have set NODE_TLS_REJECT_UNAUTHORIZED=0 .
```javascript
module.exports = {
  before: config => {
    /**
     * handle_tls_reject_unauthorized.js
     * */

    require("./config/env");

    process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = '0';
  }
}
```

Also, inside the fetching code, triggered inside react hook, I have also added `strictSSL:false`, `rejectUnauthorized:false` options.

```javascript
import https from  "https";
https.globalAgent.options.rejectUnauthorized = false;

export const ApiGET = async(route, params={}, auth=true) => {

  let opt = {params,
    headers:{
      // Authorization: auth? "Bearer "+localStorage.getItem("token"): null,
    },
    strictSSL: false,
    rejectUnauthorized: false,
    httpsAgent: new https.Agent({rejectUnauthorized:false}),
  };
  console.log(process.env["NODE_TLS_REJECT_UNAUTHORIZED"])/*?*/  //=0
  let resp =  await axios.get(`${publicUrl}/api/${route}`,opt)
    .then(resp =>{
      console.log(resp);
      return resp.data || resp;
    }
      )
    .catch(err => {
      console.log("error");
      console.error(err.response)
      return err.response.data || err.response;
    });

  return resp;
};
```
but still getting DEPTH_ZERO_SELF_SIGNED_CERT error.

My servers seems to noticing the request and successfully reply responses however my Quokka.js console replies:
```
Error: Error: SSL Error: DEPTH_ZERO_SELF_SIGNED_CERT
    at Object.dispatchError (..../node_modules/jsdom-quokka-plugin/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:60:19)
    at EventEmitter.client.on.err (..../node_modules/jsdom-quokka-plugin/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:674:20)
    at EventEmitter.emit (events.js:203:15)
    at Request.preflightClient.on.err (..../node_modules/jsdom-quokka-plugin/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:399:47)
    at Request.emit (events.js:198:13)
    at Request.onRequestResponse (..../node_modules/request/request.js:952:10)
    at ClientRequest.emit (events.js:198:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) undefined

```

Sending same request through browser or postman seems to work fine.
Is there anything I can do other than:
 - setting `DEPTH_ZERO_SELF_SIGNED_CERT=0`
 - `strictSSL: false` option in axios
 - `rejectUnauthorized: false` in axios

**Comment by smcenlly** [comment] 2020-03-25 22:04
This seems to be unrelated to Quokka. Have you tried to reproduce the problem outside of Quokka using node?

We found [this comment on axios issues](https://github.com/axios/axios/issues/535#issuecomment-599971219) from 9 days ago where someone had the same problem:

```javascript
// doesn't work
axios.create({
    httpsAgent: new https.Agent({ rejectUnauthorized: false })
});

// it works
https.globalAgent.options.rejectUnauthorized = false;
```

If that doesn't work for you, our suggestion is to try it outside of Quokka using node as you will almost certainly have the same problem. If the problem is indeed limited to Quokka, could you please provide us with a sample repo, including a server-side implementation that has the same invalid certificate setup?

I'll close this issue but will re-open if you're still having problems.

**Closed by smcenlly** 2020-03-25 22:04 UTC
