### ISSUE TITLE
normal Json Object trigger crash!

### ISSUE THREAD

**Issue by shawnlwy85** [wallabyjs/quokka#685] opened 2021-09-23 02:47 UTC
### Issue description or question

1 simple json object once place in will cause crash

The object structure is direct copy from Chrome Console
i console log the obj, then left click copy object 
so i believe it is a legit object structure, because it working on chrome.

### Sample code

_________________________________________________________________ Workable JSON Object 
const a = [
                    {
                        "num": 1,
                        "id": 3466,
                        "order_id": "475",
                        "order_type": "Sales",
                        "order_set": "",
                        "order_set_status": "undefined",
                        "item_qty": 1,
                        "item_id": "39",
                        "item_name": "SET A034 - G4560 / 8GB RAM / 120 GB SSD",
                        "item_type": "15. PC",
                        "patronName": "Muhammad Azim bin Zulkeflee",
                        "patronAddress": "Melaka, Masjid Tanah, 78300, Melaka",
                        "create_by": "jc1003@gmail.com",
                        "create_dt": "2021-07-04 17:12:48",
                        "item_sn": null,
                        "item_sn_by": null,
                        "item_sn_dt": null,
                        "order_payment_due": null,
                        "qty": 1,
                        "unit_price": 599,
                        "total_price": 599
                    },
                    {
                        "num": 2,
                        "id": 3467,
                        "order_id": "475",
                        "order_type": "Sales",
                        "order_set": "",
                        "order_set_status": "undefined",
                        "item_qty": 1,
                        "item_id": "30",
                        "item_name": "22 inch monitor",
                        "item_type": "8. MON",
                        "patronName": "Muhammad Azim bin Zulkeflee",
                        "patronAddress": "Melaka, Masjid Tanah, 78300, Melaka",
                 
                    }
                ]
_________________________________________________________________ NOT Workable JSON Object (after  "patronAddress") added in 2 nd item )

const a = [
                    {
                        "num": 1,
                        "id": 3466,
                        "order_id": "475",
                        "order_type": "Sales",
                        "order_set": "",
                        "order_set_status": "undefined",
                        "item_qty": 1,
                        "item_id": "39",
                        "item_name": "SET A034 - G4560 / 8GB RAM / 120 GB SSD",
                        "item_type": "15. PC",
                        "patronName": "Muhammad Azim bin Zulkeflee",
                        "patronAddress": "Melaka, Masjid Tanah, 78300, Melaka",
                        "create_by": "jc1003@gmail.com",
                        "create_dt": "2021-07-04 17:12:48",
                        "item_sn": null,
                        "item_sn_by": null,
                        "item_sn_dt": null,
                        "order_payment_due": null,
                        "qty": 1,
                        "unit_price": 599,
                        "total_price": 599
                    },
                    {
                        "num": 2,
                        "id": 3467,
                        "order_id": "475",
                        "order_type": "Sales",
                        "order_set": "",
                        "order_set_status": "undefined",
                        "item_qty": 1,
                        "item_id": "30",
                        "item_name": "22 inch monitor",
                        "item_type": "8. MON",
                        "patronName": "Muhammad Azim bin Zulkeflee",
                        "patronAddress": "Melaka, Masjid Tanah, 78300, Melaka",
                        "create_by": "jc1003@gmail.com",
                        "create_dt": "2021-07-04 17:12:48",
                        "item_sn": null,
                        "item_sn_by": null,
                        "item_sn_dt": null,
                        "order_payment_due": null,
                        "qty": 1,
                        "unit_price": 160,
                        "total_price": 160
                    }
                ]

```javascript
// paste the code you are running here
```

### Sample repository link

sry dont have, because it just a simple code.

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

In VS CODE

OUTPUT show blank
____________________________________ PROBLEMS pop up error below
{
	"resource": "Untitled-2",
	"owner": "_generated_diagnostic_collection_name_#1",
	"severity": 8,
	"message": "Expected a JSON object, array or literal.",
	"source": "json",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 6
}
```
// paste your quokka console output here
```

### Code editor version

Visual Studio Code v1.? 
1.60.1 

### OS name and version
Windows 10 Home Single Language
version 21H1
OS Build 19043.1237

Windows

**Comment by ArtemGovorov** [comment] 2021-09-23 02:50
The issue is related to https://github.com/microsoft/vscode/issues/132431. It's working as expected in VS Code Insiders and is fixed in VS Code v1.60.2 (please update your VS Code and the issue should be fixed for you).

**Comment by shawnlwy85** [comment] 2021-09-23 02:50
Workable 
![image](https://user-images.githubusercontent.com/49618844/134448033-adc9697d-29d3-48f3-9f42-f53db07b31e8.png)


NOT Workable
![image](https://user-images.githubusercontent.com/49618844/134448088-93b1fc66-1895-430f-940b-cbb356f9184b.png)
![image](https://user-images.githubusercontent.com/49618844/134448104-a90df171-2d5d-4445-be3b-7cb7a7c4df9e.png)

**Closed by ArtemGovorov** 2021-09-23 02:50 UTC

**Comment by shawnlwy85** [comment] 2021-09-23 02:53
Thank it fixed!
using VS Code v1.60.2

Good and Fast Response ~ appreciate very much

![image](https://user-images.githubusercontent.com/49618844/134448250-3f5031ef-defa-426a-8143-eaf7f11183be.png)
