### ISSUE TITLE
VS Code not working properly after installing Quokka

### ISSUE THREAD

**Issue by pBread** [wallabyjs/quokka#429] opened 2019-11-01 20:55 UTC
I installed Quokka and now my entire configuration is messed up. For instance, I can't have more than two windows open at a time. It looks like Quokka overrides my preference settings and has no uninstall mechanism to correct them

**Comment by smcenlly** [comment] 2019-11-01 22:33
We've not seen this issue before, can you please provide a bit more detail?

> For instance, I can't have more than two windows open at a time. 

What happens when you try open more than one window? Are you getting an error?

> It looks like Quokka overrides my preference settings and has no uninstall mechanism to correct them

Quokka does not override any of your preferences. Have you tried uninstalling Quokka? If so, did it fix your problem?

> my entire configuration is messed up

What else is going wrong besides not being able to open a second window?

---

Unrelated to Quokka, we have seen VS Code become corrupted on previous occasions. It may help to uninstall and reinstall VS Code and any extensions you have added.

Please be sure to install Quokka as your first extension and confirm that everything is working before installing other extensions.

**Comment by pBread** [comment] 2019-11-02 17:50
It is related to Quokka. You should be able to install/uninstall a package without re-installing the whole thing.

**Comment by ArtemGovorov** [comment] 2019-11-03 01:00
> It is related to Quokka. You should be able to install/uninstall a package without re-installing the whole thing.

Could you please provide the details [requested above](https://github.com/wallabyjs/quokka/issues/429#issuecomment-548972834)? As @smcenlly had mentioned, Quokka does not override any of your preferences, so if the issue is indeed related to Quokka, we need this information to start the investigation.

**Comment by pBread** [comment] 2019-11-03 22:16
I’ve seen this issue before. The last time I installed Quokka (a year ago)
it demolished my settings & I had to reinstall.

**Comment by smcenlly** [comment] 2019-11-03 22:22
We are keen to identify the cause of this issue and resolve the problem. Could you please provide the details [requested above](https://github.com/wallabyjs/quokka/issues/429#issuecomment-548972834)? If you are unable to provide further detail we will not be able to progress further.

**Comment by smcenlly** [comment] 2019-11-05 23:16
I'm closing this issue as we do not have enough information to proceed with investigation. If you reply to this issue with the details requested, we will reopen the issue.

**Closed by smcenlly** 2019-11-05 23:16 UTC
