### ISSUE TITLE
JavaScript file turns into TypeScript file

### ISSUE THREAD

**Issue by nevvv** [wallabyjs/quokka#683] opened 2021-09-21 10:53 UTC
If you paste my code below into a new quokka JavaScript file the code will run and give the correct out put for a split second before the file changes into a TypeScript file.
```
const numArr = [1, 3, 5, 7, 8, 9, 10];
const sum = 14;

function twosum(arr, sum) {
  for (let i = 0; i < arr.length; i++) {
    let currentNum = arr[i];
    arr.splice(0, 1);
    for (const num of arr) {
      if (currentNum + num === sum) {
        console.log(`answer is: ${currentNum} & ${num}`);
        return;
      }
    }
  }
}

twosum(numArr, sum);
```
![image](https://user-images.githubusercontent.com/64247023/134157803-b000155a-d2bb-4c5c-854d-92bf5bc308d6.png)

### Quokka.js Console Output

```
answer is: 5 & 9 ​​​​​at ​​​​​​​​`answer is: ${ currentNum } & ${ num }`​​​ [​quokka.js:10:8​]
```

Changing my function name to ```sumtwo``` or any other name fixes this issue.

### Code editor version

Visual Studio Code v1.60.1

### OS name and version

Windows_NT x64 10.0.19042

**Comment by ArtemGovorov** [comment] 2021-09-21 11:01
The issue is related to https://github.com/microsoft/vscode/issues/132431. It's working as expected in VS Code Insiders and is fixed in VS Code v1.60.2.

**Closed by ArtemGovorov** 2021-09-21 11:01 UTC
